### PR TITLE
credentials: Require credentials file has restricted permissions.

### LINKED ISSUE #50: Better solution than always looking in the same place for credentials
Umut brought up a good point, that if we always look ~/.diderot/credentials, then that will encourage students to store their passwords in that location. However, that location by default is not private on AFS, and it could lead to students seeing other student's passwords. We need a way to work around this.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #50.

### CODE REVIEW

**Comment by rohany** [comment]
Ok, let me update this -- it is replicated in order to print a different error message. When the user passes a credentials file and that file path is not valid we want to notify the user. However if none of the default files are found we don't want to print anything.

**Comment by rohany** [comment]
Updated

**Comment by gauravmm** [comment]
You can check and give separate error messages by testing `self.args.credentials` later on and printing a message accordingly. Or you can abstract the credential check into a separate function.

**Comment by rohany** [comment]
Ok, I fixed that duplication. Thanks for the review!

**Pull request merged**
