### PR TITLE
Bulk book uploads

### PR DESCRIPTION
**Pull request by umutacar**
This PR implements support book uploads with parts.  See  as example
```
testdata/book-with-parts.json
```

### CODE REVIEW

**Comment by rohany** [comment]
Do you know why the tests have started to fail? Or were they failing already?

**Comment by umutacar** [comment]
I don't know why/how they started failing :(

**Comment by rohany** [comment]
I guess we can merge this and spend some time on the main PR figuring out why they have failed.

**Comment by umutacar** [comment]
here is the commit where tests first fail.   not sure why
https://github.com/diderot-edu/diderot-cli/pull/71/commits/8468a09f510ff9e65a6ba22c584c7660f531f82e

**Pull request merged**
