### PR TITLE
admin: add a prototype for bulk chapter uploads

### PR DESCRIPTION
**Pull request by rohany**
The new command can be used with 
```
diderot_admin upload_book course_label path/to/json/file
```

TODO:
- [x] set path to that of the json
- [x] extend to take into account parts so that books can be uploaded

### CODE REVIEW

**Comment by rohany** [comment]
@umutacar please check out this branch and give this a try. I'll wait for this to stabilize more before adding unit + integration tests with diderot.

**Comment by rohany** [comment]
This will only work right now on booklets, if a new chapter has to be created (non booklets need a part number when creating a chapter).

**Comment by rohany** [comment]
An example of the json format i'm parsing is `testdata/bulk_upload.json`

**Comment by umutacar** [comment]
Nice concept!  I added a `testdata/book` directory to try out.  
See `book.json`, 
For attachments, the format i have used for chapter 3 worked but not for chapter 4 .  i am not sure why.

**Comment by rohany** [comment]
> For attachments, the format i have used for chapter 3 worked but not for chapter 4 . i am not sure why.

What do you mean? The attachments for chapter 3 are the same as attachments for chapter 4 in book.json

Also, please don't include this whole directory of testdata in this repository -- this data belongs in the Diderot repository test directory where we can actually upload this data to a real running diderot instance (the tests here upload dummy files to a dummy diderot instance).

A limitation right now is that the paths in the json file are relative to the cwd of the caller, not the location of the json file.

**Comment by umutacar** [comment]
`git pull` again, the `book.json` was not pushed.  we can delete this after
we are done.  cancel culture it is called.

-- Umut

**Comment by rohany** [comment]
Sounds good -- it's probably not working because of "A limitation right now is that the paths in the json file are relative to the cwd of the caller, not the location of the json file."

**Comment by umutacar** [comment]
i doubt that that is the problem.  i accounted for that.  the first and the
second chapter attachments are wrt to the same but the first works, the
second doesn't.

-- Umut

**Comment by rohany** [comment]
It doesn't look like `media-augment/bst5-build.jpg` or `media-augment/treap-examp.jpg` are valid paths in `media-augment/`. However, I'm confused why you aren't seeing some error message that these files don't exist.

**Comment by rohany** [comment]
> extend to take into account parts so that books can be uploaded

We'll need to include part numbers in the JSON then

I have this set up right now that the JSON file can contain multiple books worth of chapters. I see that you have renamed the command to `upload_book` -- do you want me to get rid of that ability, or name the command to something else?

**Comment by umutacar** [comment]
Yes, let's do single booklet and book uploads (no need for multiple books).

**Comment by rohany** [comment]
Take another try at this @umutacar (i included your changes). Now,
* file paths are relative to the location of the JSON file
* if the target book has parts and 'part' isn't specific in the chapter JSON an error is thrown
* if a specified attachment is missing or an empty glob is provided an error is thrown and the upload is aborted
* renamed to upload_book and removed the outer list (look at `bulk_test/bulk_upload.json`)

**Comment by rohany** [comment]
cc @umutacar did you give this a try? Should I merge it?

**Comment by umutacar** [comment]
@rohany sorry it took me a long time to get back to this.  i wanted to test it a bit before we merge.  There seems to be a bug but I am not sure where.  I will email with more details.

**Comment by umutacar** [comment]
looked into this a bit more.  there seems to be a small error with the API.  if the PDF file is not valid then the API should return a 40X (406 probably) but it seem to return 200.  would be nice to add a test for this.  a good invalid PDF file is an "empty" one.  This comes up pretty frequently (forgotten "include" in latex source).

**Comment by rohany** [comment]
Glad you found it -- is there an issue to track that test addition for the API?

**Comment by umutacar** [comment]
created an issue on the diderot repo.  do we need one here as well?

**Comment by rohany** [comment]
No, that's fine.

**Comment by umutacar** [comment]
Superseded by #80

**Pull request closed without merging**
